# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Tag
version:      1.02
version_from: Tag.pm
installdirs:  site
requires:
    Class::AutoAccess:             0
    Tie::IxHash:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
